title                    : "QiChao Yuan"
name                     : &name "QiChao Yuan"
description              : &description "QiChao Yuan's academic homepage"
url                      : "https://yuanqichao197-del.github.io"
baseurl                  : ""
repository               : "yuanqichao197-del/yuanqichao197-del.github.io"
